# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Corne/Documents/MEGA/4. Semester/Digital/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/Master/Master.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master || ORIG_REF_NAME==Master} -quiet] -quiet

# IP: bd/Master/ip/Master_shift_register_gener_0_0/Master_shift_register_gener_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_shift_register_gener_0_0 || ORIG_REF_NAME==Master_shift_register_gener_0_0} -quiet] -quiet

# IP: bd/Master/ip/Master_latch_0_0/Master_latch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_latch_0_0 || ORIG_REF_NAME==Master_latch_0_0} -quiet] -quiet

# IP: bd/Master/ip/Master_prescaler_0_0/Master_prescaler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_prescaler_0_0 || ORIG_REF_NAME==Master_prescaler_0_0} -quiet] -quiet

# IP: bd/Master/ip/Master_Chip_Select_0_0/Master_Chip_Select_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_Chip_Select_0_0 || ORIG_REF_NAME==Master_Chip_Select_0_0} -quiet] -quiet

# IP: bd/Master/ip/Master_NOT_gate_0_0/Master_NOT_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_NOT_gate_0_0 || ORIG_REF_NAME==Master_NOT_gate_0_0} -quiet] -quiet

# IP: bd/Master/ip/Master_rx_mod_0_0/Master_rx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_rx_mod_0_0 || ORIG_REF_NAME==Master_rx_mod_0_0} -quiet] -quiet

# IP: bd/Master/ip/Master_tx_mod_0_0/Master_tx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_tx_mod_0_0 || ORIG_REF_NAME==Master_tx_mod_0_0} -quiet] -quiet

# IP: bd/Master/ip/Master_clock_div_0_0/Master_clock_div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_clock_div_0_0 || ORIG_REF_NAME==Master_clock_div_0_0} -quiet] -quiet

# IP: bd/Master/ip/Master_clock_div_1_0/Master_clock_div_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_clock_div_1_0 || ORIG_REF_NAME==Master_clock_div_1_0} -quiet] -quiet

# IP: bd/Master/ip/Master_AND_gate_0_0/Master_AND_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_AND_gate_0_0 || ORIG_REF_NAME==Master_AND_gate_0_0} -quiet] -quiet

# IP: bd/Master/ip/Master_AND_gate_0_1/Master_AND_gate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_AND_gate_0_1 || ORIG_REF_NAME==Master_AND_gate_0_1} -quiet] -quiet

# IP: bd/Master/ip/Master_NOT_gate_0_1/Master_NOT_gate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Master_NOT_gate_0_1 || ORIG_REF_NAME==Master_NOT_gate_0_1} -quiet] -quiet

# XDC: c:/Users/Corne/Documents/MEGA/4. Semester/Digital/FPGA_1_MASTER/FPGA_1_MASTER.gen/sources_1/bd/Master/Master_ooc.xdc
