# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Corne/Documents/MEGA/4. Semester/Digital/SPI_Assignment/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/assignment_3/assignment_3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3 || ORIG_REF_NAME==assignment_3} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_SPI_sub_0/assignment_3_SPI_sub_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_SPI_sub_0 || ORIG_REF_NAME==assignment_3_SPI_sub_0} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_synchronizer_0_0/assignment_3_synchronizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_synchronizer_0_0 || ORIG_REF_NAME==assignment_3_synchronizer_0_0} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_synchronizer_0_1/assignment_3_synchronizer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_synchronizer_0_1 || ORIG_REF_NAME==assignment_3_synchronizer_0_1} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_synchronizer_0_2/assignment_3_synchronizer_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_synchronizer_0_2 || ORIG_REF_NAME==assignment_3_synchronizer_0_2} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_synchronizer_0_3/assignment_3_synchronizer_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_synchronizer_0_3 || ORIG_REF_NAME==assignment_3_synchronizer_0_3} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_Rising_edge_detector_0_0/assignment_3_Rising_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_Rising_edge_detector_0_0 || ORIG_REF_NAME==assignment_3_Rising_edge_detector_0_0} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_Falling_edge_detector_0_0/assignment_3_Falling_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_Falling_edge_detector_0_0 || ORIG_REF_NAME==assignment_3_Falling_edge_detector_0_0} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_rx_mod_0_0/assignment_3_rx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_rx_mod_0_0 || ORIG_REF_NAME==assignment_3_rx_mod_0_0} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_latch_1_0_0/assignment_3_latch_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_latch_1_0_0 || ORIG_REF_NAME==assignment_3_latch_1_0_0} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_AND_gate_0_0/assignment_3_AND_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_AND_gate_0_0 || ORIG_REF_NAME==assignment_3_AND_gate_0_0} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_tx_mod_0_0/assignment_3_tx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_tx_mod_0_0 || ORIG_REF_NAME==assignment_3_tx_mod_0_0} -quiet] -quiet

# IP: bd/assignment_3/ip/assignment_3_clock_div_0_1/assignment_3_clock_div_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==assignment_3_clock_div_0_1 || ORIG_REF_NAME==assignment_3_clock_div_0_1} -quiet] -quiet

# XDC: c:/Users/Corne/Documents/MEGA/4. Semester/Digital/SPI_Assignment/SPI_sub/SPI_sub.gen/sources_1/bd/assignment_3/assignment_3_ooc.xdc
