# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jacob/Documents/Semester4/FPGA/Assignment_3/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/sub_spi/sub_spi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi || ORIG_REF_NAME==sub_spi} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_fsm_template_0_0/sub_spi_fsm_template_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_fsm_template_0_0 || ORIG_REF_NAME==sub_spi_fsm_template_0_0} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_synchronizer_0_0/sub_spi_synchronizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_synchronizer_0_0 || ORIG_REF_NAME==sub_spi_synchronizer_0_0} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_synchronizer_0_1/sub_spi_synchronizer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_synchronizer_0_1 || ORIG_REF_NAME==sub_spi_synchronizer_0_1} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_synchronizer_0_2/sub_spi_synchronizer_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_synchronizer_0_2 || ORIG_REF_NAME==sub_spi_synchronizer_0_2} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_Rising_edge_detector_0_0/sub_spi_Rising_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_Rising_edge_detector_0_0 || ORIG_REF_NAME==sub_spi_Rising_edge_detector_0_0} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_Falling_edge_detector_0_0/sub_spi_Falling_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_Falling_edge_detector_0_0 || ORIG_REF_NAME==sub_spi_Falling_edge_detector_0_0} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_tx_mod_0_0/sub_spi_tx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_tx_mod_0_0 || ORIG_REF_NAME==sub_spi_tx_mod_0_0} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_clock_div_0_0/sub_spi_clock_div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_clock_div_0_0 || ORIG_REF_NAME==sub_spi_clock_div_0_0} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_rx_mod_0_0/sub_spi_rx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_rx_mod_0_0 || ORIG_REF_NAME==sub_spi_rx_mod_0_0} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_synchronizer_0_3/sub_spi_synchronizer_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_synchronizer_0_3 || ORIG_REF_NAME==sub_spi_synchronizer_0_3} -quiet] -quiet

# IP: bd/sub_spi/ip/sub_spi_AND_gate_0_0/sub_spi_AND_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_spi_AND_gate_0_0 || ORIG_REF_NAME==sub_spi_AND_gate_0_0} -quiet] -quiet

# XDC: /home/jacob/Documents/Semester4/FPGA/Assignment_3/SPI_sub/SPI_sub.gen/sources_1/bd/sub_spi/sub_spi_ooc.xdc
